name: Load SQL Data to PostgreSQL

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  load_sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Crear archivo clave SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > EC2_SSH_KEY.pem
          chmod 600 EC2_SSH_KEY.pem

      - name: listar archivos .sql
        run: |
          # Listamos los archivos .sql en la carpeta sql/
          echo "Archivos SQL encontrados:"
          ls -1 sql/*.sql    


      - name: Copiar archivos .sql a EC2
        run: |
          # Copiamos todos los .sql que estén en la carpeta sql/ del repo a /tmp/ en EC2
          scp -o StrictHostKeyChecking=no -i EC2_SSH_KEY.pem sql/*.sql ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

      - name: Ejecutar scripts SQL dentro del contenedor PostgreSQL en EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i EC2_SSH_KEY.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            for sqlfile in /tmp/*.sql; do
              echo "Ejecutando \$sqlfile en el contenedor postgresql-dev"
              docker cp "\$sqlfile" postgresql-dev:/tmp/
              docker exec -u postgres postgresql-dev psql 
              -d ${{ secrets.POSTGRES_DB }} 
              -f /tmp/\$(basename \$sqlfile)
            done
          EOF
